### ISSUE TITLE
Importing the plugin causes the app to crash on Android (NativeScript 6)

### ISSUE THREAD

**Issue by tommag21** [Notalib/nativescript-accessibility-ext#41]
### Which platform(s) does your issue occur on?
- Android (8.1, 9)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.2.0
- Cross-platform modules: 6.1.2
- Runtime: 6.1.2

### Please, tell us how to recreate the issue in as much detail as possible. 
Importing the plugin causes the app to crash. I read around it might be related to the switch to `androidx`.

### Is there any code involved? 
`require("@nota/nativescript-accessibility-ext");`

Produces this error:
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'accessibility' of undefined
System.err: File: (file:///app\utils.android.ts:8:59)
System.err: 
System.err: StackTrace:
System.err:     ../node_modules/@nota/nativescript-accessibility-ext/utils/utils.js(file:///app\utils.android.ts:8:59)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:74:0)
System.err:     at ../node_modules/@nota/nativescript-accessibility-ext/utils/index.js(file:///app\index.ts:1:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:74:0)
System.err:     at ../node_modules/@nota/nativescript-accessibility-ext/index.js(file:///app\index.ts:3:0)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:74:0)
System.err:     at (file:///app\main.js:65:29)
System.err:     at ./main.js(file:///data/data/it.convergence1.rossi/files/app/bundle.js:16338:30)
System.err:     at __webpack_require__(file:///app\webpack\bootstrap:74:0)
System.err:     at checkDeferredModules(file:///app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/it.convergence1.rossi/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
```

**Comment by m-abs** [comment]
Try updating to NativeScript 6.2.

The latest version of the plugin switched to the new scoped import paths.

**Comment by tommag21** [comment]
Thanks, now it woks!
